/**
 * generated by Xtext 2.9.1
 */
package com.nukulargames.gdx4e.actors.dsl;

import com.nukulargames.gdx4e.actors.dsl.AbstractDslRuntimeModule;
import com.nukulargames.gdx4e.actors.dsl.generator.DslGenerator;
import com.nukulargames.gdx4e.actors.dsl.jvmmodel.ActorInferrer;
import org.eclipse.xtext.generator.IGenerator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DslRuntimeModule extends AbstractDslRuntimeModule {
  @Override
  public Class<? extends IGenerator> bindIGenerator() {
    return DslGenerator.class;
  }
  
  public Class<ActorInferrer> bindActorInferrer() {
    return ActorInferrer.class;
  }
}
