/**
 * generated by Xtext 2.9.1
 */
package com.nukulargames.gdx4e.actors.dsl;

import com.nukulargames.gdx4e.actors.dsl.DslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DslStandaloneSetup extends DslStandaloneSetupGenerated {
  public static void doSetup() {
    DslStandaloneSetup _dslStandaloneSetup = new DslStandaloneSetup();
    _dslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
