/*
 * generated by Xtext 2.9.1
 */
package com.nukulargames.gdx4e.actors.dsl.scoping;

import org.eclipse.xtext.xbase.annotations.typesystem.XbaseWithAnnotationsBatchScopeProvider;

public abstract class AbstractDslScopeProvider extends XbaseWithAnnotationsBatchScopeProvider {
}
