/*
 * generated by Xtext 2.9.1
 */
package com.nukulargames.gdx4e.actors.dsl.ui.tests;

import com.google.inject.Injector;
import com.nukulargames.gdx4e.actors.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class DslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("com.nukulargames.gdx4e.actors.dsl.Dsl");
	}

}
