/**
 * generated by Xtext 2.9.1
 */
package com.nukulargames.gdx4e.actors.dsl.jvmmodel;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.Batch;
import com.badlogic.gdx.graphics.g2d.TextureRegion;
import com.google.inject.Inject;
import com.nukulargames.gdx4e.actors.Actor;
import com.nukulargames.gdx4e.actors.ActorsFactory;
import com.nukulargames.gdx4e.actors.Animation;
import com.nukulargames.gdx4e.actors.Model;
import com.nukulargames.gdx4e.actors.State;
import com.nukulargames.gdx4e.ext.NukuActor;
import java.util.Arrays;
import java.util.List;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtend2.lib.StringConcatenationClient;
import org.eclipse.xtext.common.types.JvmConstructor;
import org.eclipse.xtext.common.types.JvmDeclaredType;
import org.eclipse.xtext.common.types.JvmEnumerationLiteral;
import org.eclipse.xtext.common.types.JvmEnumerationType;
import org.eclipse.xtext.common.types.JvmField;
import org.eclipse.xtext.common.types.JvmFormalParameter;
import org.eclipse.xtext.common.types.JvmGenericType;
import org.eclipse.xtext.common.types.JvmMember;
import org.eclipse.xtext.common.types.JvmOperation;
import org.eclipse.xtext.common.types.JvmTypeReference;
import org.eclipse.xtext.common.types.JvmVisibility;
import org.eclipse.xtext.xbase.jvmmodel.AbstractModelInferrer;
import org.eclipse.xtext.xbase.jvmmodel.IJvmDeclaredTypeAcceptor;
import org.eclipse.xtext.xbase.jvmmodel.IJvmDeclaredTypeAcceptor.IPostIndexingInitializing;
import org.eclipse.xtext.xbase.jvmmodel.JvmTypesBuilder;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.Functions.Function2;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.ListExtensions;
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;
import org.eclipse.xtext.xbase.lib.StringExtensions;

/**
 * <p>Infers a JVM model from the source model.</p>
 * 
 * <p>The JVM model should contain all elements that would appear in the Java code
 * which is generated from the source model. Other models link against the JVM model rather than the source model.</p>
 */
@SuppressWarnings("all")
public class DslJvmModelInferrer extends AbstractModelInferrer {
  /**
   * convenience API to build and initialize JVM types and their members.
   */
  @Inject
  @Extension
  private JvmTypesBuilder _jvmTypesBuilder;
  
  @Extension
  private ActorsFactory factory = ActorsFactory.eINSTANCE;
  
  /**
   * The dispatch method {@code infer} is called for each instance of the
   * given element's type that is contained in a resource.
   * 
   * @param element
   *            the model to create one or more
   *            {@link JvmDeclaredType declared
   *            types} from.
   * @param acceptor
   *            each created
   *            {@link JvmDeclaredType type}
   *            without a container should be passed to the acceptor in order
   *            get attached to the current resource. The acceptor's
   *            {@link IJvmDeclaredTypeAcceptor#accept(org.eclipse.xtext.common.types.JvmDeclaredType)
   *            accept(..)} method takes the constructed empty type for the
   *            pre-indexing phase. This one is further initialized in the
   *            indexing phase using the closure you pass to the returned
   *            {@link IPostIndexingInitializing#initializeLater(org.eclipse.xtext.xbase.lib.Procedures.Procedure1)
   *            initializeLater(..)}.
   * @param isPreIndexingPhase
   *            whether the method is called in a pre-indexing phase, i.e.
   *            when the global index is not yet fully actd. You must not
   *            rely on linking using the index if isPreIndexingPhase is
   *            <code>true</code>.
   */
  protected void _infer(final Model element, final IJvmDeclaredTypeAcceptor acceptor, final boolean isPreIndexingPhase) {
    EList<Actor> _actors = element.getActors();
    for (final Actor actor : _actors) {
      this.infer(element, actor, acceptor, isPreIndexingPhase);
    }
  }
  
  public void infer(final Model model, final Actor element, final IJvmDeclaredTypeAcceptor acceptor, final boolean isPreIndexingPhase) {
    String _basePackageName = this.basePackageName(model);
    String _name = element.getName();
    String _plus = (_basePackageName + _name);
    String _plus_1 = (_plus + "Gen");
    final JvmGenericType genClass = this._jvmTypesBuilder.toClass(element, _plus_1);
    final Procedure1<JvmGenericType> _function = (JvmGenericType it) -> {
      EList<JvmTypeReference> _superTypes = it.getSuperTypes();
      JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(NukuActor.class);
      this._jvmTypesBuilder.<JvmTypeReference>operator_add(_superTypes, _typeRef);
      EList<JvmMember> _members = it.getMembers();
      JvmEnumerationType _stateEnum = this.stateEnum(element);
      this._jvmTypesBuilder.<JvmEnumerationType>operator_add(_members, _stateEnum);
      EList<JvmMember> _members_1 = it.getMembers();
      JvmField _currentState = this.currentState(element);
      this._jvmTypesBuilder.<JvmField>operator_add(_members_1, _currentState);
      EList<JvmMember> _members_2 = it.getMembers();
      List<JvmField> _textureFields = this.textureFields(element);
      this._jvmTypesBuilder.<JvmMember>operator_add(_members_2, _textureFields);
      EList<JvmMember> _members_3 = it.getMembers();
      List<JvmField> _animationFields = this.animationFields(element);
      this._jvmTypesBuilder.<JvmMember>operator_add(_members_3, _animationFields);
      EList<JvmMember> _members_4 = it.getMembers();
      JvmField _currentAnimationField = this.currentAnimationField(element);
      this._jvmTypesBuilder.<JvmField>operator_add(_members_4, _currentAnimationField);
      EList<JvmMember> _members_5 = it.getMembers();
      JvmField _stateTimeField = this.stateTimeField(element);
      this._jvmTypesBuilder.<JvmField>operator_add(_members_5, _stateTimeField);
      EList<JvmMember> _members_6 = it.getMembers();
      JvmConstructor _constructor = this.constructor(element);
      this._jvmTypesBuilder.<JvmConstructor>operator_add(_members_6, _constructor);
      EList<JvmMember> _members_7 = it.getMembers();
      JvmOperation _initPosition = this.initPosition(element);
      this._jvmTypesBuilder.<JvmOperation>operator_add(_members_7, _initPosition);
      EList<JvmMember> _members_8 = it.getMembers();
      JvmOperation _initSize = this.initSize(element);
      this._jvmTypesBuilder.<JvmOperation>operator_add(_members_8, _initSize);
      EList<JvmMember> _members_9 = it.getMembers();
      JvmOperation _initScale = this.initScale(element);
      this._jvmTypesBuilder.<JvmOperation>operator_add(_members_9, _initScale);
      EList<JvmMember> _members_10 = it.getMembers();
      JvmOperation _initRotation = this.initRotation(element);
      this._jvmTypesBuilder.<JvmOperation>operator_add(_members_10, _initRotation);
      EList<JvmMember> _members_11 = it.getMembers();
      JvmOperation _initColor = this.initColor(element);
      this._jvmTypesBuilder.<JvmOperation>operator_add(_members_11, _initColor);
      EList<JvmMember> _members_12 = it.getMembers();
      JvmOperation _initState = this.initState(element);
      this._jvmTypesBuilder.<JvmOperation>operator_add(_members_12, _initState);
      EList<JvmMember> _members_13 = it.getMembers();
      List<JvmOperation> _animation = this.getAnimation(element);
      this._jvmTypesBuilder.<JvmMember>operator_add(_members_13, _animation);
      EList<JvmMember> _members_14 = it.getMembers();
      JvmOperation _draw = this.draw(element);
      this._jvmTypesBuilder.<JvmOperation>operator_add(_members_14, _draw);
      EList<JvmMember> _members_15 = it.getMembers();
      List<JvmOperation> _drawState = this.drawState(element);
      this._jvmTypesBuilder.<JvmMember>operator_add(_members_15, _drawState);
      EList<JvmMember> _members_16 = it.getMembers();
      JvmOperation _drawAnimation = this.drawAnimation(element);
      this._jvmTypesBuilder.<JvmOperation>operator_add(_members_16, _drawAnimation);
      EList<JvmMember> _members_17 = it.getMembers();
      JvmOperation _act = this.act(element);
      this._jvmTypesBuilder.<JvmOperation>operator_add(_members_17, _act);
      EList<JvmMember> _members_18 = it.getMembers();
      List<JvmOperation> __actState = this._actState(element);
      this._jvmTypesBuilder.<JvmMember>operator_add(_members_18, __actState);
      EList<JvmMember> _members_19 = it.getMembers();
      List<JvmOperation> _actState = this.actState(element);
      this._jvmTypesBuilder.<JvmMember>operator_add(_members_19, _actState);
      EList<JvmMember> _members_20 = it.getMembers();
      JvmOperation _resetStateTime = this.resetStateTime(element);
      this._jvmTypesBuilder.<JvmOperation>operator_add(_members_20, _resetStateTime);
      EList<JvmMember> _members_21 = it.getMembers();
      JvmOperation _currentState_1 = this.getCurrentState(element);
      this._jvmTypesBuilder.<JvmOperation>operator_add(_members_21, _currentState_1);
      EList<JvmMember> _members_22 = it.getMembers();
      JvmOperation _transit = this.transit(element);
      this._jvmTypesBuilder.<JvmOperation>operator_add(_members_22, _transit);
      EList<JvmMember> _members_23 = it.getMembers();
      List<JvmOperation> __enterState = this._enterState(element);
      this._jvmTypesBuilder.<JvmMember>operator_add(_members_23, __enterState);
      EList<JvmMember> _members_24 = it.getMembers();
      List<JvmOperation> _enterState = this.enterState(element);
      this._jvmTypesBuilder.<JvmMember>operator_add(_members_24, _enterState);
      EList<JvmMember> _members_25 = it.getMembers();
      List<JvmOperation> __leaveState = this._leaveState(element);
      this._jvmTypesBuilder.<JvmMember>operator_add(_members_25, __leaveState);
      EList<JvmMember> _members_26 = it.getMembers();
      List<JvmOperation> _leaveState = this.leaveState(element);
      this._jvmTypesBuilder.<JvmMember>operator_add(_members_26, _leaveState);
    };
    acceptor.<JvmGenericType>accept(genClass, _function);
    String _basePackageName_1 = this.basePackageName(model);
    String _name_1 = element.getName();
    String _plus_2 = (_basePackageName_1 + _name_1);
    JvmGenericType _class = this._jvmTypesBuilder.toClass(element, _plus_2);
    final Procedure1<JvmGenericType> _function_1 = (JvmGenericType it) -> {
      EList<JvmTypeReference> _superTypes = it.getSuperTypes();
      JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(genClass);
      this._jvmTypesBuilder.<JvmTypeReference>operator_add(_superTypes, _typeRef);
    };
    acceptor.<JvmGenericType>accept(_class, _function_1);
  }
  
  public String basePackageName(final Model model) {
    String _xifexpression = null;
    String _basePackage = model.getBasePackage();
    boolean _isNullOrEmpty = StringExtensions.isNullOrEmpty(_basePackage);
    if (_isNullOrEmpty) {
      _xifexpression = "";
    } else {
      String _basePackage_1 = model.getBasePackage();
      _xifexpression = (_basePackage_1 + ".");
    }
    return _xifexpression;
  }
  
  public JvmEnumerationType stateEnum(final Actor actor) {
    final Procedure1<JvmEnumerationType> _function = (JvmEnumerationType it) -> {
      EList<JvmMember> _members = it.getMembers();
      EList<State> _normalizedStates = actor.getNormalizedStates();
      final Function1<State, JvmEnumerationLiteral> _function_1 = (State s) -> {
        String _name = s.getName();
        String _upperCase = _name.toUpperCase();
        return this._jvmTypesBuilder.toEnumerationLiteral(actor, _upperCase);
      };
      List<JvmEnumerationLiteral> _map = ListExtensions.<State, JvmEnumerationLiteral>map(_normalizedStates, _function_1);
      this._jvmTypesBuilder.<JvmMember>operator_add(_members, _map);
    };
    return this._jvmTypesBuilder.toEnumerationType(actor, "States", _function);
  }
  
  public JvmField currentState(final Actor actor) {
    JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef("States");
    final Procedure1<JvmField> _function = (JvmField it) -> {
      it.setVisibility(JvmVisibility.PRIVATE);
      StringConcatenationClient _client = new StringConcatenationClient() {
        @Override
        protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
          _builder.append("null");
        }
      };
      this._jvmTypesBuilder.setInitializer(it, _client);
    };
    return this._jvmTypesBuilder.toField(actor, "currentState", _typeRef, _function);
  }
  
  public List<JvmField> textureFields(final Actor actor) {
    EList<Animation> _normalizedAnimations = actor.getNormalizedAnimations();
    final Function1<Animation, JvmField> _function = (Animation a) -> {
      String _name = a.getName();
      String _upperCase = _name.toUpperCase();
      String _plus = (_upperCase + "_TEXTURE");
      JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(Texture.class);
      final Procedure1<JvmField> _function_1 = (JvmField it) -> {
        it.setVisibility(JvmVisibility.PRIVATE);
        it.setFinal(true);
        it.setStatic(true);
        StringConcatenationClient _client = new StringConcatenationClient() {
          @Override
          protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
            _builder.append("new ");
            _builder.append(Texture.class, "");
            _builder.append("(");
            _builder.append(Gdx.class, "");
            _builder.append(".files.internal(\"");
            String _elvis = null;
            String _texture = a.getTexture();
            if (_texture != null) {
              _elvis = _texture;
            } else {
              String _name = actor.getName();
              String _name_1 = actor.getName();
              int _lastIndexOf = _name_1.lastIndexOf(".");
              int _plus = (_lastIndexOf + 1);
              String _substring = _name.substring(_plus);
              String _plus_1 = (_substring + "_");
              String _name_2 = a.getName();
              String _plus_2 = (_plus_1 + _name_2);
              String _plus_3 = (_plus_2 + ".png");
              _elvis = _plus_3;
            }
            _builder.append(_elvis, "");
            _builder.append("\"))");
          }
        };
        this._jvmTypesBuilder.setInitializer(it, _client);
      };
      return this._jvmTypesBuilder.toField(actor, _plus, _typeRef, _function_1);
    };
    return ListExtensions.<Animation, JvmField>map(_normalizedAnimations, _function);
  }
  
  public List<JvmField> animationFields(final Actor actor) {
    EList<Animation> _normalizedAnimations = actor.getNormalizedAnimations();
    final Function1<Animation, JvmField> _function = (Animation a) -> {
      String _name = a.getName();
      String _firstLower = StringExtensions.toFirstLower(_name);
      String _plus = (_firstLower + "Animation");
      JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(com.badlogic.gdx.graphics.g2d.Animation.class);
      final Procedure1<JvmField> _function_1 = (JvmField it) -> {
        it.setVisibility(JvmVisibility.PRIVATE);
        it.setFinal(true);
      };
      return this._jvmTypesBuilder.toField(actor, _plus, _typeRef, _function_1);
    };
    return ListExtensions.<Animation, JvmField>map(_normalizedAnimations, _function);
  }
  
  public JvmField stateTimeField(final Actor actor) {
    JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(float.class);
    final Procedure1<JvmField> _function = (JvmField it) -> {
      it.setVisibility(JvmVisibility.PRIVATE);
      StringConcatenationClient _client = new StringConcatenationClient() {
        @Override
        protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
          _builder.append("0.0f");
        }
      };
      this._jvmTypesBuilder.setInitializer(it, _client);
    };
    return this._jvmTypesBuilder.toField(actor, "animationStateTime", _typeRef, _function);
  }
  
  public JvmField currentAnimationField(final Actor actor) {
    JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(com.badlogic.gdx.graphics.g2d.Animation.class);
    return this._jvmTypesBuilder.toField(actor, "currentAnimation", _typeRef);
  }
  
  public JvmConstructor constructor(final Actor actor) {
    final Procedure1<JvmConstructor> _function = (JvmConstructor it) -> {
      it.setVisibility(JvmVisibility.PUBLIC);
      StringConcatenationClient _client = new StringConcatenationClient() {
        @Override
        protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
          _builder.append("super();");
          _builder.newLine();
          String _createAnimationCalls = DslJvmModelInferrer.this.createAnimationCalls(actor);
          _builder.append(_createAnimationCalls, "");
          _builder.newLineIfNotEmpty();
          _builder.append("initState();");
          _builder.newLine();
        }
      };
      this._jvmTypesBuilder.setBody(it, _client);
    };
    return this._jvmTypesBuilder.toConstructor(actor, _function);
  }
  
  public String createAnimationCalls(final Actor actor) {
    EList<Animation> _normalizedAnimations = actor.getNormalizedAnimations();
    final Function1<Animation, String> _function = (Animation a) -> {
      String _name = a.getName();
      String _firstLower = StringExtensions.toFirstLower(_name);
      String _plus = (_firstLower + "Animation = createAnimation(");
      String _name_1 = a.getName();
      String _upperCase = _name_1.toUpperCase();
      String _plus_1 = (_plus + _upperCase);
      String _plus_2 = (_plus_1 + "_TEXTURE, ");
      int _rows = a.getRows();
      String _plus_3 = (_plus_2 + Integer.valueOf(_rows));
      String _plus_4 = (_plus_3 + ", ");
      int _columns = a.getColumns();
      String _plus_5 = (_plus_4 + Integer.valueOf(_columns));
      String _plus_6 = (_plus_5 + ", (float) ");
      float _delay = a.getDelay();
      String _plus_7 = (_plus_6 + Float.valueOf(_delay));
      return (_plus_7 + ");");
    };
    List<String> _map = ListExtensions.<Animation, String>map(_normalizedAnimations, _function);
    final Function2<String, String, String> _function_1 = (String in, String line) -> {
      return ((in + "\n") + line);
    };
    return IterableExtensions.<String, String>fold(_map, "", _function_1);
  }
  
  public JvmOperation initPosition(final Actor actor) {
    JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(void.class);
    final Procedure1<JvmOperation> _function = (JvmOperation it) -> {
      it.setVisibility(JvmVisibility.PROTECTED);
      this._annotationTypesBuilder.annotationRef(Override.class);
      StringConcatenationClient _client = new StringConcatenationClient() {
        @Override
        protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
          _builder.append("setX((float) ");
          float _x = actor.getX();
          _builder.append(_x, "");
          _builder.append(");");
          _builder.newLineIfNotEmpty();
          _builder.append("setY((float) ");
          float _y = actor.getY();
          _builder.append(_y, "");
          _builder.append(");");
          _builder.newLineIfNotEmpty();
        }
      };
      this._jvmTypesBuilder.setBody(it, _client);
    };
    return this._jvmTypesBuilder.toMethod(actor, "initPosition", _typeRef, _function);
  }
  
  public JvmOperation initSize(final Actor actor) {
    JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(void.class);
    final Procedure1<JvmOperation> _function = (JvmOperation it) -> {
      it.setVisibility(JvmVisibility.PROTECTED);
      this._annotationTypesBuilder.annotationRef(Override.class);
      StringConcatenationClient _client = new StringConcatenationClient() {
        @Override
        protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
          _builder.append("setWidth((float) ");
          float _width = actor.getWidth();
          _builder.append(_width, "");
          _builder.append(");");
          _builder.newLineIfNotEmpty();
          _builder.append("setHeight((float) ");
          float _height = actor.getHeight();
          _builder.append(_height, "");
          _builder.append(");");
          _builder.newLineIfNotEmpty();
        }
      };
      this._jvmTypesBuilder.setBody(it, _client);
    };
    return this._jvmTypesBuilder.toMethod(actor, "initSize", _typeRef, _function);
  }
  
  public JvmOperation initScale(final Actor actor) {
    JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(void.class);
    final Procedure1<JvmOperation> _function = (JvmOperation it) -> {
      it.setVisibility(JvmVisibility.PROTECTED);
      this._annotationTypesBuilder.annotationRef(Override.class);
      StringConcatenationClient _client = new StringConcatenationClient() {
        @Override
        protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
          _builder.append("setScaleX((float) ");
          float _scaleX = actor.getScaleX();
          _builder.append(_scaleX, "");
          _builder.append(");");
          _builder.newLineIfNotEmpty();
          _builder.append("setScaleY((float) ");
          float _scaleY = actor.getScaleY();
          _builder.append(_scaleY, "");
          _builder.append(");");
          _builder.newLineIfNotEmpty();
        }
      };
      this._jvmTypesBuilder.setBody(it, _client);
    };
    return this._jvmTypesBuilder.toMethod(actor, "initScale", _typeRef, _function);
  }
  
  public JvmOperation initRotation(final Actor actor) {
    JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(void.class);
    final Procedure1<JvmOperation> _function = (JvmOperation it) -> {
      it.setVisibility(JvmVisibility.PROTECTED);
      this._annotationTypesBuilder.annotationRef(Override.class);
      StringConcatenationClient _client = new StringConcatenationClient() {
        @Override
        protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
          _builder.append("setRotation((float) ");
          float _rotation = actor.getRotation();
          _builder.append(_rotation, "");
          _builder.append(");");
          _builder.newLineIfNotEmpty();
        }
      };
      this._jvmTypesBuilder.setBody(it, _client);
    };
    return this._jvmTypesBuilder.toMethod(actor, "initRotation", _typeRef, _function);
  }
  
  public JvmOperation initColor(final Actor actor) {
    JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(void.class);
    final Procedure1<JvmOperation> _function = (JvmOperation it) -> {
      it.setVisibility(JvmVisibility.PROTECTED);
      this._annotationTypesBuilder.annotationRef(Override.class);
      StringConcatenationClient _client = new StringConcatenationClient() {
        @Override
        protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
          _builder.append("setColor((float) ");
          float _red = actor.getRed();
          _builder.append(_red, "");
          _builder.append(", (float) ");
          float _green = actor.getGreen();
          _builder.append(_green, "");
          _builder.append(", (float) ");
          float _blue = actor.getBlue();
          _builder.append(_blue, "");
          _builder.append(", (float) ");
          float _alpha = actor.getAlpha();
          _builder.append(_alpha, "");
          _builder.append(");");
          _builder.newLineIfNotEmpty();
        }
      };
      this._jvmTypesBuilder.setBody(it, _client);
    };
    return this._jvmTypesBuilder.toMethod(actor, "initColor", _typeRef, _function);
  }
  
  public JvmOperation initState(final Actor actor) {
    JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(void.class);
    final Procedure1<JvmOperation> _function = (JvmOperation it) -> {
      it.setVisibility(JvmVisibility.PROTECTED);
      StringConcatenationClient _client = new StringConcatenationClient() {
        @Override
        protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
          String _elvis = null;
          String _elvis_1 = null;
          State _defaultState = null;
          if (actor!=null) {
            _defaultState=actor.getDefaultState();
          }
          String _name = null;
          if (_defaultState!=null) {
            _name=_defaultState.getName();
          }
          String _firstUpper = null;
          if (_name!=null) {
            _firstUpper=StringExtensions.toFirstUpper(_name);
          }
          if (_firstUpper != null) {
            _elvis_1 = _firstUpper;
          } else {
            EList<State> _states = null;
            if (actor!=null) {
              _states=actor.getStates();
            }
            State _head = null;
            if (_states!=null) {
              _head=IterableExtensions.<State>head(_states);
            }
            String _name_1 = null;
            if (_head!=null) {
              _name_1=_head.getName();
            }
            String _firstUpper_1 = null;
            if (_name_1!=null) {
              _firstUpper_1=StringExtensions.toFirstUpper(_name_1);
            }
            _elvis_1 = _firstUpper_1;
          }
          if (_elvis_1 != null) {
            _elvis = _elvis_1;
          } else {
            _elvis = "Default";
          }
          final String stateName = _elvis;
          _builder.newLineIfNotEmpty();
          _builder.append("_enter");
          _builder.append(stateName, "");
          _builder.append("State();");
          _builder.newLineIfNotEmpty();
        }
      };
      this._jvmTypesBuilder.setBody(it, _client);
    };
    return this._jvmTypesBuilder.toMethod(actor, "initState", _typeRef, _function);
  }
  
  public List<JvmOperation> getAnimation(final Actor actor) {
    EList<Animation> _animations = actor.getAnimations();
    final Function1<Animation, JvmOperation> _function = (Animation a) -> {
      String _name = a.getName();
      String _firstUpper = StringExtensions.toFirstUpper(_name);
      String _plus = ("get" + _firstUpper);
      String _plus_1 = (_plus + "Animation");
      JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(com.badlogic.gdx.graphics.g2d.Animation.class);
      final Procedure1<JvmOperation> _function_1 = (JvmOperation it) -> {
        it.setVisibility(JvmVisibility.PUBLIC);
        StringConcatenationClient _client = new StringConcatenationClient() {
          @Override
          protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
            _builder.append("return ");
            String _name = a.getName();
            String _firstLower = StringExtensions.toFirstLower(_name);
            _builder.append(_firstLower, "");
            _builder.append("Animation;");
            _builder.newLineIfNotEmpty();
          }
        };
        this._jvmTypesBuilder.setBody(it, _client);
      };
      return this._jvmTypesBuilder.toMethod(actor, _plus_1, _typeRef, _function_1);
    };
    return ListExtensions.<Animation, JvmOperation>map(_animations, _function);
  }
  
  public JvmOperation getCurrentState(final Actor actor) {
    JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef("States");
    final Procedure1<JvmOperation> _function = (JvmOperation it) -> {
      StringConcatenationClient _client = new StringConcatenationClient() {
        @Override
        protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
          _builder.append("return currentState;");
          _builder.newLine();
        }
      };
      this._jvmTypesBuilder.setBody(it, _client);
    };
    return this._jvmTypesBuilder.toMethod(actor, "getCurrentState", _typeRef, _function);
  }
  
  public JvmOperation transit(final Actor actor) {
    JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(void.class);
    final Procedure1<JvmOperation> _function = (JvmOperation it) -> {
      EList<JvmFormalParameter> _parameters = it.getParameters();
      JvmTypeReference _typeRef_1 = this._typeReferenceBuilder.typeRef("States");
      JvmFormalParameter _parameter = this._jvmTypesBuilder.toParameter(actor, "next", _typeRef_1);
      this._jvmTypesBuilder.<JvmFormalParameter>operator_add(_parameters, _parameter);
      StringConcatenationClient _client = new StringConcatenationClient() {
        @Override
        protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
          _builder.append("switch (currentState) {");
          _builder.newLine();
          {
            EList<State> _normalizedStates = actor.getNormalizedStates();
            for(final State state : _normalizedStates) {
              _builder.append("\t");
              _builder.append("case ");
              String _name = state.getName();
              String _upperCase = _name.toUpperCase();
              _builder.append(_upperCase, "\t");
              _builder.append(":");
              _builder.newLineIfNotEmpty();
              _builder.append("\t");
              _builder.append("\t");
              _builder.append("_leave");
              String _name_1 = state.getName();
              String _firstUpper = StringExtensions.toFirstUpper(_name_1);
              _builder.append(_firstUpper, "\t\t");
              _builder.append("State();");
              _builder.newLineIfNotEmpty();
              _builder.append("\t");
              _builder.append("\t");
              _builder.append("break;");
              _builder.newLine();
            }
          }
          _builder.append("\t");
          _builder.append("default:");
          _builder.newLine();
          _builder.append("}");
          _builder.newLine();
          _builder.newLine();
          _builder.append("switch (next) {");
          _builder.newLine();
          {
            EList<State> _normalizedStates_1 = actor.getNormalizedStates();
            for(final State state_1 : _normalizedStates_1) {
              _builder.append("\t");
              _builder.append("case ");
              String _name_2 = state_1.getName();
              String _upperCase_1 = _name_2.toUpperCase();
              _builder.append(_upperCase_1, "\t");
              _builder.append(":");
              _builder.newLineIfNotEmpty();
              _builder.append("\t");
              _builder.append("\t");
              _builder.append("_enter");
              String _name_3 = state_1.getName();
              String _firstUpper_1 = StringExtensions.toFirstUpper(_name_3);
              _builder.append(_firstUpper_1, "\t\t");
              _builder.append("State();");
              _builder.newLineIfNotEmpty();
              _builder.append("\t");
              _builder.append("\t");
              _builder.append("break;");
              _builder.newLine();
            }
          }
          _builder.append("\t");
          _builder.append("default:");
          _builder.newLine();
          _builder.append("}");
          _builder.newLine();
        }
      };
      this._jvmTypesBuilder.setBody(it, _client);
    };
    return this._jvmTypesBuilder.toMethod(actor, "transit", _typeRef, _function);
  }
  
  public List<JvmOperation> _enterState(final Actor actor) {
    EList<State> _normalizedStates = actor.getNormalizedStates();
    final Function1<State, JvmOperation> _function = (State s) -> {
      String _name = s.getName();
      String _firstUpper = StringExtensions.toFirstUpper(_name);
      String _plus = ("_enter" + _firstUpper);
      String _plus_1 = (_plus + "State");
      JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(void.class);
      final Procedure1<JvmOperation> _function_1 = (JvmOperation it) -> {
        it.setVisibility(JvmVisibility.PROTECTED);
        StringConcatenationClient _client = new StringConcatenationClient() {
          @Override
          protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
            _builder.append("currentAnimation = ");
            Animation _animationForState = DslJvmModelInferrer.this.animationForState(actor, s);
            String _name = _animationForState.getName();
            String _firstLower = StringExtensions.toFirstLower(_name);
            _builder.append(_firstLower, "");
            _builder.append("Animation;");
            _builder.newLineIfNotEmpty();
            _builder.append("resetStateTime();");
            _builder.newLine();
            _builder.append("enter");
            String _name_1 = s.getName();
            String _firstUpper = StringExtensions.toFirstUpper(_name_1);
            _builder.append(_firstUpper, "");
            _builder.append("State();");
            _builder.newLineIfNotEmpty();
            _builder.append("currentState = States.");
            String _name_2 = s.getName();
            String _upperCase = _name_2.toUpperCase();
            _builder.append(_upperCase, "");
            _builder.append(";");
            _builder.newLineIfNotEmpty();
          }
        };
        this._jvmTypesBuilder.setBody(it, _client);
      };
      return this._jvmTypesBuilder.toMethod(actor, _plus_1, _typeRef, _function_1);
    };
    return ListExtensions.<State, JvmOperation>map(_normalizedStates, _function);
  }
  
  public List<JvmOperation> enterState(final Actor actor) {
    EList<State> _normalizedStates = actor.getNormalizedStates();
    final Function1<State, JvmOperation> _function = (State s) -> {
      String _name = s.getName();
      String _firstUpper = StringExtensions.toFirstUpper(_name);
      String _plus = ("enter" + _firstUpper);
      String _plus_1 = (_plus + "State");
      JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(void.class);
      final Procedure1<JvmOperation> _function_1 = (JvmOperation it) -> {
        it.setVisibility(JvmVisibility.PROTECTED);
        StringConcatenationClient _client = new StringConcatenationClient() {
          @Override
          protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
          }
        };
        this._jvmTypesBuilder.setBody(it, _client);
      };
      return this._jvmTypesBuilder.toMethod(actor, _plus_1, _typeRef, _function_1);
    };
    return ListExtensions.<State, JvmOperation>map(_normalizedStates, _function);
  }
  
  public Animation animationForState(final Actor actor, final State state) {
    Animation _elvis = null;
    Animation _animation = state.getAnimation();
    if (_animation != null) {
      _elvis = _animation;
    } else {
      EList<Animation> _animations = actor.getAnimations();
      final Function1<Animation, Boolean> _function = (Animation a) -> {
        String _name = a.getName();
        String _name_1 = state.getName();
        return Boolean.valueOf(_name.equals(_name_1));
      };
      Animation _findFirst = IterableExtensions.<Animation>findFirst(_animations, _function);
      _elvis = _findFirst;
    }
    return _elvis;
  }
  
  public List<JvmOperation> _leaveState(final Actor actor) {
    EList<State> _normalizedStates = actor.getNormalizedStates();
    final Function1<State, JvmOperation> _function = (State s) -> {
      String _name = s.getName();
      String _firstUpper = StringExtensions.toFirstUpper(_name);
      String _plus = ("_leave" + _firstUpper);
      String _plus_1 = (_plus + "State");
      JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(void.class);
      final Procedure1<JvmOperation> _function_1 = (JvmOperation it) -> {
        it.setVisibility(JvmVisibility.PROTECTED);
        StringConcatenationClient _client = new StringConcatenationClient() {
          @Override
          protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
            _builder.append("leave");
            String _name = s.getName();
            String _firstUpper = StringExtensions.toFirstUpper(_name);
            _builder.append(_firstUpper, "");
            _builder.append("State();");
            _builder.newLineIfNotEmpty();
          }
        };
        this._jvmTypesBuilder.setBody(it, _client);
      };
      return this._jvmTypesBuilder.toMethod(actor, _plus_1, _typeRef, _function_1);
    };
    return ListExtensions.<State, JvmOperation>map(_normalizedStates, _function);
  }
  
  public List<JvmOperation> leaveState(final Actor actor) {
    EList<State> _normalizedStates = actor.getNormalizedStates();
    final Function1<State, JvmOperation> _function = (State s) -> {
      String _name = s.getName();
      String _firstUpper = StringExtensions.toFirstUpper(_name);
      String _plus = ("leave" + _firstUpper);
      String _plus_1 = (_plus + "State");
      JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(void.class);
      final Procedure1<JvmOperation> _function_1 = (JvmOperation it) -> {
        it.setVisibility(JvmVisibility.PROTECTED);
        StringConcatenationClient _client = new StringConcatenationClient() {
          @Override
          protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
          }
        };
        this._jvmTypesBuilder.setBody(it, _client);
      };
      return this._jvmTypesBuilder.toMethod(actor, _plus_1, _typeRef, _function_1);
    };
    return ListExtensions.<State, JvmOperation>map(_normalizedStates, _function);
  }
  
  public JvmOperation draw(final Actor actor) {
    JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(void.class);
    final Procedure1<JvmOperation> _function = (JvmOperation it) -> {
      EList<JvmFormalParameter> _parameters = it.getParameters();
      JvmTypeReference _typeRef_1 = this._typeReferenceBuilder.typeRef(Batch.class);
      JvmFormalParameter _parameter = this._jvmTypesBuilder.toParameter(actor, "batch", _typeRef_1);
      this._jvmTypesBuilder.<JvmFormalParameter>operator_add(_parameters, _parameter);
      EList<JvmFormalParameter> _parameters_1 = it.getParameters();
      JvmTypeReference _typeRef_2 = this._typeReferenceBuilder.typeRef(float.class);
      JvmFormalParameter _parameter_1 = this._jvmTypesBuilder.toParameter(actor, "parentAlpha", _typeRef_2);
      this._jvmTypesBuilder.<JvmFormalParameter>operator_add(_parameters_1, _parameter_1);
      it.setVisibility(JvmVisibility.PUBLIC);
      this._annotationTypesBuilder.annotationRef(Override.class);
      StringConcatenationClient _client = new StringConcatenationClient() {
        @Override
        protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
          CharSequence _drawStateCalls = DslJvmModelInferrer.this.drawStateCalls(actor);
          _builder.append(_drawStateCalls, "");
        }
      };
      this._jvmTypesBuilder.setBody(it, _client);
    };
    return this._jvmTypesBuilder.toMethod(actor, "draw", _typeRef, _function);
  }
  
  public CharSequence drawStateCalls(final Actor actor) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("switch (currentState) {");
    _builder.newLine();
    {
      EList<State> _normalizedStates = actor.getNormalizedStates();
      for(final State state : _normalizedStates) {
        _builder.append("\t");
        _builder.append("case ");
        String _name = state.getName();
        String _upperCase = _name.toUpperCase();
        _builder.append(_upperCase, "\t");
        _builder.append(":");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("draw");
        String _name_1 = state.getName();
        String _firstUpper = StringExtensions.toFirstUpper(_name_1);
        _builder.append(_firstUpper, "\t\t");
        _builder.append("State(batch, parentAlpha);");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("break;");
        _builder.newLine();
      }
    }
    _builder.append("\t");
    _builder.append("default:");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("super.draw(batch, parentAlpha);");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public List<JvmOperation> drawState(final Actor actor) {
    EList<State> _normalizedStates = actor.getNormalizedStates();
    final Function1<State, JvmOperation> _function = (State s) -> {
      String _name = s.getName();
      String _firstUpper = StringExtensions.toFirstUpper(_name);
      String _plus = ("draw" + _firstUpper);
      String _plus_1 = (_plus + "State");
      JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(void.class);
      final Procedure1<JvmOperation> _function_1 = (JvmOperation it) -> {
        EList<JvmFormalParameter> _parameters = it.getParameters();
        JvmTypeReference _typeRef_1 = this._typeReferenceBuilder.typeRef(Batch.class);
        JvmFormalParameter _parameter = this._jvmTypesBuilder.toParameter(actor, "batch", _typeRef_1);
        this._jvmTypesBuilder.<JvmFormalParameter>operator_add(_parameters, _parameter);
        EList<JvmFormalParameter> _parameters_1 = it.getParameters();
        JvmTypeReference _typeRef_2 = this._typeReferenceBuilder.typeRef(float.class);
        JvmFormalParameter _parameter_1 = this._jvmTypesBuilder.toParameter(actor, "parentAlpha", _typeRef_2);
        this._jvmTypesBuilder.<JvmFormalParameter>operator_add(_parameters_1, _parameter_1);
        it.setVisibility(JvmVisibility.PROTECTED);
        StringConcatenationClient _client = new StringConcatenationClient() {
          @Override
          protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
            _builder.append("drawAnimation(batch, parentAlpha, currentAnimation);");
          }
        };
        this._jvmTypesBuilder.setBody(it, _client);
      };
      return this._jvmTypesBuilder.toMethod(actor, _plus_1, _typeRef, _function_1);
    };
    return ListExtensions.<State, JvmOperation>map(_normalizedStates, _function);
  }
  
  public JvmOperation drawAnimation(final Actor actor) {
    JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(void.class);
    final Procedure1<JvmOperation> _function = (JvmOperation it) -> {
      EList<JvmFormalParameter> _parameters = it.getParameters();
      JvmTypeReference _typeRef_1 = this._typeReferenceBuilder.typeRef(Batch.class);
      JvmFormalParameter _parameter = this._jvmTypesBuilder.toParameter(actor, "batch", _typeRef_1);
      this._jvmTypesBuilder.<JvmFormalParameter>operator_add(_parameters, _parameter);
      EList<JvmFormalParameter> _parameters_1 = it.getParameters();
      JvmTypeReference _typeRef_2 = this._typeReferenceBuilder.typeRef(float.class);
      JvmFormalParameter _parameter_1 = this._jvmTypesBuilder.toParameter(actor, "parentAlpha", _typeRef_2);
      this._jvmTypesBuilder.<JvmFormalParameter>operator_add(_parameters_1, _parameter_1);
      EList<JvmFormalParameter> _parameters_2 = it.getParameters();
      JvmTypeReference _typeRef_3 = this._typeReferenceBuilder.typeRef(com.badlogic.gdx.graphics.g2d.Animation.class);
      JvmFormalParameter _parameter_2 = this._jvmTypesBuilder.toParameter(actor, "animation", _typeRef_3);
      this._jvmTypesBuilder.<JvmFormalParameter>operator_add(_parameters_2, _parameter_2);
      it.setVisibility(JvmVisibility.PROTECTED);
      StringConcatenationClient _client = new StringConcatenationClient() {
        @Override
        protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
          _builder.append("if (animation != null) {");
          _builder.newLine();
          _builder.append("\t");
          _builder.append("final ");
          _builder.append(TextureRegion.class, "\t");
          _builder.append(" region = animation.getKeyFrame(animationStateTime, true);");
          _builder.newLineIfNotEmpty();
          _builder.append("\t");
          _builder.append(Color.class, "\t");
          _builder.append(" tint = batch.getColor();");
          _builder.newLineIfNotEmpty();
          _builder.append("\t");
          _builder.append("batch.setColor(getColor());");
          _builder.newLine();
          _builder.append("\t");
          _builder.append("batch.draw(region, getX(), getY(), getOriginX(), getOriginY(), getWidth(), getHeight(), getScaleX(), getScaleY(), getRotation());");
          _builder.newLine();
          _builder.append("\t");
          _builder.append("batch.setColor(tint);");
          _builder.newLine();
          _builder.append("}");
          _builder.newLine();
        }
      };
      this._jvmTypesBuilder.setBody(it, _client);
    };
    return this._jvmTypesBuilder.toMethod(actor, "drawAnimation", _typeRef, _function);
  }
  
  public JvmOperation act(final Actor actor) {
    JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(void.class);
    final Procedure1<JvmOperation> _function = (JvmOperation it) -> {
      EList<JvmFormalParameter> _parameters = it.getParameters();
      JvmTypeReference _typeRef_1 = this._typeReferenceBuilder.typeRef(float.class);
      JvmFormalParameter _parameter = this._jvmTypesBuilder.toParameter(actor, "delta", _typeRef_1);
      this._jvmTypesBuilder.<JvmFormalParameter>operator_add(_parameters, _parameter);
      it.setVisibility(JvmVisibility.PUBLIC);
      this._annotationTypesBuilder.annotationRef(Override.class);
      StringConcatenationClient _client = new StringConcatenationClient() {
        @Override
        protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
          CharSequence _actStateCalls = DslJvmModelInferrer.this.actStateCalls(actor);
          _builder.append(_actStateCalls, "");
        }
      };
      this._jvmTypesBuilder.setBody(it, _client);
    };
    return this._jvmTypesBuilder.toMethod(actor, "act", _typeRef, _function);
  }
  
  public CharSequence actStateCalls(final Actor actor) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("switch (currentState) {");
    _builder.newLine();
    {
      EList<State> _normalizedStates = actor.getNormalizedStates();
      for(final State state : _normalizedStates) {
        _builder.append("\t");
        _builder.append("case ");
        String _name = state.getName();
        String _upperCase = _name.toUpperCase();
        _builder.append(_upperCase, "\t");
        _builder.append(":");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("_act");
        String _name_1 = state.getName();
        String _firstUpper = StringExtensions.toFirstUpper(_name_1);
        _builder.append(_firstUpper, "\t\t");
        _builder.append("State(delta);");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("\t");
        _builder.append("break;");
        _builder.newLine();
      }
    }
    _builder.append("\t");
    _builder.append("default:");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("super.act(delta);");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
  
  public List<JvmOperation> _actState(final Actor actor) {
    EList<State> _normalizedStates = actor.getNormalizedStates();
    final Function1<State, JvmOperation> _function = (State s) -> {
      String _name = s.getName();
      String _firstUpper = StringExtensions.toFirstUpper(_name);
      String _plus = ("_act" + _firstUpper);
      String _plus_1 = (_plus + "State");
      JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(void.class);
      final Procedure1<JvmOperation> _function_1 = (JvmOperation it) -> {
        EList<JvmFormalParameter> _parameters = it.getParameters();
        JvmTypeReference _typeRef_1 = this._typeReferenceBuilder.typeRef(float.class);
        JvmFormalParameter _parameter = this._jvmTypesBuilder.toParameter(actor, "delta", _typeRef_1);
        this._jvmTypesBuilder.<JvmFormalParameter>operator_add(_parameters, _parameter);
        it.setVisibility(JvmVisibility.PROTECTED);
        StringConcatenationClient _client = new StringConcatenationClient() {
          @Override
          protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
            _builder.append("animationStateTime += delta;");
            _builder.newLine();
            _builder.append("act");
            String _name = s.getName();
            String _firstUpper = StringExtensions.toFirstUpper(_name);
            _builder.append(_firstUpper, "");
            _builder.append("State(delta);");
            _builder.newLineIfNotEmpty();
          }
        };
        this._jvmTypesBuilder.setBody(it, _client);
      };
      return this._jvmTypesBuilder.toMethod(actor, _plus_1, _typeRef, _function_1);
    };
    return ListExtensions.<State, JvmOperation>map(_normalizedStates, _function);
  }
  
  public List<JvmOperation> actState(final Actor actor) {
    EList<State> _normalizedStates = actor.getNormalizedStates();
    final Function1<State, JvmOperation> _function = (State s) -> {
      String _name = s.getName();
      String _firstUpper = StringExtensions.toFirstUpper(_name);
      String _plus = ("act" + _firstUpper);
      String _plus_1 = (_plus + "State");
      JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(void.class);
      final Procedure1<JvmOperation> _function_1 = (JvmOperation it) -> {
        EList<JvmFormalParameter> _parameters = it.getParameters();
        JvmTypeReference _typeRef_1 = this._typeReferenceBuilder.typeRef(float.class);
        JvmFormalParameter _parameter = this._jvmTypesBuilder.toParameter(actor, "delta", _typeRef_1);
        this._jvmTypesBuilder.<JvmFormalParameter>operator_add(_parameters, _parameter);
        it.setVisibility(JvmVisibility.PROTECTED);
        StringConcatenationClient _client = new StringConcatenationClient() {
          @Override
          protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
          }
        };
        this._jvmTypesBuilder.setBody(it, _client);
      };
      return this._jvmTypesBuilder.toMethod(actor, _plus_1, _typeRef, _function_1);
    };
    return ListExtensions.<State, JvmOperation>map(_normalizedStates, _function);
  }
  
  public JvmOperation resetStateTime(final Actor actor) {
    JvmTypeReference _typeRef = this._typeReferenceBuilder.typeRef(void.class);
    final Procedure1<JvmOperation> _function = (JvmOperation it) -> {
      StringConcatenationClient _client = new StringConcatenationClient() {
        @Override
        protected void appendTo(StringConcatenationClient.TargetStringConcatenation _builder) {
          _builder.append("animationStateTime = 0.0f;");
        }
      };
      this._jvmTypesBuilder.setBody(it, _client);
    };
    return this._jvmTypesBuilder.toMethod(actor, "resetStateTime", _typeRef, _function);
  }
  
  public void infer(final EObject element, final IJvmDeclaredTypeAcceptor acceptor, final boolean isPreIndexingPhase) {
    if (element instanceof Model) {
      _infer((Model)element, acceptor, isPreIndexingPhase);
      return;
    } else if (element != null) {
      _infer(element, acceptor, isPreIndexingPhase);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(element, acceptor, isPreIndexingPhase).toString());
    }
  }
}
