/**
 * generated by Xtext 2.9.1
 */
package com.nukulargames.gdx4e.actors.dsl.ui;

import com.google.inject.Binder;
import com.google.inject.Singleton;
import com.google.inject.binder.AnnotatedBindingBuilder;
import com.google.inject.binder.ScopedBindingBuilder;
import com.nukulargames.gdx4e.actors.dsl.generator.Stage2dOutputConfigurationProvider;
import com.nukulargames.gdx4e.actors.dsl.ui.AbstractDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.generator.IOutputConfigurationProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DslUiModule extends AbstractDslUiModule {
  @Override
  public void configure(final Binder binder) {
    super.configure(binder);
    AnnotatedBindingBuilder<IOutputConfigurationProvider> _bind = binder.<IOutputConfigurationProvider>bind(IOutputConfigurationProvider.class);
    ScopedBindingBuilder _to = _bind.to(Stage2dOutputConfigurationProvider.class);
    _to.in(Singleton.class);
  }
  
  public DslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
