/**
 * generated by Xtext 2.9.1
 */
package com.nukulargames.gdx4e.actors.dsl.scoping;

import com.nukulargames.gdx4e.actors.dsl.scoping.AbstractDslScopeProvider;

@SuppressWarnings("all")
public class DslScopeProvider extends AbstractDslScopeProvider {
}
