/**
 * generated by Xtext 2.9.1
 */
package com.nukulargames.gdx4e.actors.dsl.validation;

import com.nukulargames.gdx4e.actors.dsl.validation.AbstractDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DslValidator extends AbstractDslValidator {
}
